### ISSUE TITLE
Build error in Node 6.2.0

### ISSUE THREAD

**Issue by lhm** [esnunes/my-proxy#3]
I'm getting the following error when installing using node 6.2.0:

```
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/my-proxy/node_modules/babel/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:fsevents@0.3.6 fsevents@0.3.6 install: `node-gyp rebuild`
npm WARN install:fsevents@0.3.6 Exit status 1
```

If I read the dependencies correctly, this seems to stem from an oldish version of Babel?
https://github.com/babel/babel/releases

**Comment by diegodoumecq** [comment]
Using node version 8.7 has the same issue

**Comment by diegodoumecq** [comment]
Alright, just sent a PR that fixes it: https://github.com/esnunes/my-proxy/pull/4
